### ISSUE TITLE
WAC and Gredwitch's stuff helicopters loose blades when entering new chunk

### ISSUE THREAD

**Issue by Kreozel** [meetric1/gmod-infinite-map#125]
Idk how it wasn't reported before or it's only me having this issue, but whenever I use any kind of WAC/Gredwitch helicopter and enter new chunk it looses the blade on the tail and helicopter goes crazy. I think it's some issue with entity transportation between chunks + some of helicopter blades and even parts count as different entity. Any idea how to solve it? Just really wanted to have some fun with helicopters on infmap! Thanks for understanding!
P.s. planes usually work just fine. As far as I know it's some issue with hp system related to different helecopter parts (enteties) which break up once new chunk is reached. Some helicopters like KA50 with no additional enteties seems to work properly? (Actually no. It takes damage and spins around...)

**Comment by meetric1** [comment]
wac blades use a source internal entity to detect collision (which I cant detour) meaning they collide with things in all chunks (trust me, I tried fixing it). As for gredwitch I recall the base just not working at all and I think the confliction is on their end.

Unfortunately you'll just have to stick with using planes, sorry

**Comment by Kreozel** [comment]
> No problem! Your mod is amazing anyways! It's very sad that Source is so much limited. Thanks you for your answer and your job whatsoever!
