### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by Glaynder** [meetric1/gmod-infinite-map#130]
I decided to upload my own map using this addon. I did everything exactly according to the instructions in github. I used the 64-bit version of Garry's Mod. But for some reason after I went to the map all the textures were intertwined with each other. However, the collision seems to remain in place. I also turned off all the addons I had.

![gm_infmap_objexample0000](https://github.com/meetric1/gmod-infinite-map/assets/51336880/23682ad2-75cb-4a35-968d-8af0f1e20393)

**Comment by meetric1** [comment]
2 possible reasons:
1. Your textures aren't being exported from blender properly
2. You are over the maximum triangle limit per material

**Comment by xCeezyx** [comment]
You need to split up the mesh so its not above the triangle limit

**Comment by Glaynder** [comment]
I solved this problem. Yes, it was a matter of a large number of triangles. Now the map loads without bugs. I also have a question related to the parkour mod "beatrun". Since this mod is not optimized for your mod, after going beyond the boundaries of the main map, some scripts broke and the character, for example, could not climb any surface. Is it possible to somehow optimize it for your mod?
